import { createFileRoute } from "@tanstack/react-router";
import { ShieldCheck, AlertTriangle, Eye, Gauge, UserCheck, Scale } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { PageHeader } from "@/components/page-header";

export const Route = createFileRoute("/responsible")({
  head: () => ({
    meta: [
      { title: "Responsible AI · AI Workplace" },
      { name: "description", content: "AI disclaimer, confidence indicators, limitations and human review guidance." },
    ],
  }),
  component: Responsible,
});

const confidence = [
  { label: "Summarization tasks", value: 88 },
  { label: "Action item extraction", value: 82 },
  { label: "Tone-controlled email drafts", value: 90 },
  { label: "Strategic recommendations", value: 64 },
];

const limitations = [
  "Models may hallucinate facts, owners, dates, or figures not present in your input.",
  "Outputs reflect training data — they may not match the latest events or your company's policies.",
  "Sensitive judgments (legal, medical, financial, HR) require qualified human review.",
  "Tone and nuance can be off for unfamiliar audiences or cultures.",
];

const practices = [
  { icon: UserCheck, title: "Human-in-the-loop", body: "Every generated email, decision summary or plan is editable and intended for human review before action." },
  { icon: Eye, title: "Transparent prompts", body: "The exact system prompt behind each feature is published in the Prompt Lab." },
  { icon: Scale, title: "No silent automation", body: "Workflows always present output for confirmation — nothing is sent or scheduled automatically." },
  { icon: Gauge, title: "Confidence signaling", body: "We flag tasks where model reliability is historically lower so you know where to look twice." },
];

function Responsible() {
  return (
    <div className="max-w-6xl mx-auto">
      <PageHeader
        eyebrow="Trust & Safety"
        title="Responsible AI Center"
        description="What this assistant can and can't do — and how to keep humans firmly in the loop."
      />

      <Card className="glass border-border/60 p-6 mb-6 border-l-4 border-l-amber-400/70">
        <div className="flex gap-4">
          <AlertTriangle className="h-5 w-5 text-amber-400 shrink-0 mt-0.5" />
          <div>
            <h2 className="font-semibold">AI Disclaimer</h2>
            <p className="text-sm text-muted-foreground mt-1.5">
              Output from the AI Workplace Command Center is generated by large language models and may contain errors, omissions, or biased framings.
              Always review AI-generated content before sending, sharing, or making decisions based on it. You — not the AI — are accountable for the result.
            </p>
          </div>
        </div>
      </Card>

      <div className="grid lg:grid-cols-2 gap-6 mb-6">
        <Card className="glass border-border/60 p-6">
          <div className="flex items-center gap-2 mb-4">
            <Gauge className="h-4 w-4 text-primary" />
            <h2 className="font-semibold">Confidence Indicators</h2>
          </div>
          <ul className="space-y-4">
            {confidence.map((c) => (
              <li key={c.label}>
                <div className="flex justify-between text-sm mb-1.5">
                  <span>{c.label}</span>
                  <span className="text-muted-foreground">{c.value}%</span>
                </div>
                <Progress value={c.value} className="h-1.5" />
              </li>
            ))}
          </ul>
          <p className="text-xs text-muted-foreground mt-4">
            Confidence is indicative — calibrated from internal evaluation runs, not a guarantee.
          </p>
        </Card>

        <Card className="glass border-border/60 p-6">
          <div className="flex items-center gap-2 mb-4">
            <AlertTriangle className="h-4 w-4 text-amber-400" />
            <h2 className="font-semibold">Known Limitations</h2>
          </div>
          <ul className="space-y-3">
            {limitations.map((l, i) => (
              <li key={i} className="text-sm flex gap-3">
                <span className="text-amber-400 mt-0.5">•</span>
                <span className="text-foreground/90">{l}</span>
              </li>
            ))}
          </ul>
        </Card>
      </div>

      <Card className="glass border-border/60 p-6">
        <div className="flex items-center gap-2 mb-4">
          <ShieldCheck className="h-4 w-4 text-accent" />
          <h2 className="font-semibold">Our Responsible AI Practices</h2>
        </div>
        <div className="grid md:grid-cols-2 gap-4">
          {practices.map((p) => (
            <div key={p.title} className="rounded-xl border border-border/60 bg-muted/20 p-4">
              <div className="flex items-center gap-2 mb-1.5">
                <p.icon className="h-4 w-4 text-primary" />
                <h3 className="font-medium text-sm">{p.title}</h3>
              </div>
              <p className="text-sm text-muted-foreground">{p.body}</p>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}
