/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as ResponsibleRouteImport } from './routes/responsible'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as EmailRouteImport } from './routes/email'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleRoute = ResponsibleRouteImport.update({
  id: '/responsible',
  path: '/responsible',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/email': typeof EmailRoute
  '/meetings': typeof MeetingsRoute
  '/planner': typeof PlannerRoute
  '/prompts': typeof PromptsRoute
  '/research': typeof ResearchRoute
  '/responsible': typeof ResponsibleRoute
  '/workflow': typeof WorkflowRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/email': typeof EmailRoute
  '/meetings': typeof MeetingsRoute
  '/planner': typeof PlannerRoute
  '/prompts': typeof PromptsRoute
  '/research': typeof ResearchRoute
  '/responsible': typeof ResponsibleRoute
  '/workflow': typeof WorkflowRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/email': typeof EmailRoute
  '/meetings': typeof MeetingsRoute
  '/planner': typeof PlannerRoute
  '/prompts': typeof PromptsRoute
  '/research': typeof ResearchRoute
  '/responsible': typeof ResponsibleRoute
  '/workflow': typeof WorkflowRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/email'
    | '/meetings'
    | '/planner'
    | '/prompts'
    | '/research'
    | '/responsible'
    | '/workflow'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/email'
    | '/meetings'
    | '/planner'
    | '/prompts'
    | '/research'
    | '/responsible'
    | '/workflow'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/email'
    | '/meetings'
    | '/planner'
    | '/prompts'
    | '/research'
    | '/responsible'
    | '/workflow'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  EmailRoute: typeof EmailRoute
  MeetingsRoute: typeof MeetingsRoute
  PlannerRoute: typeof PlannerRoute
  PromptsRoute: typeof PromptsRoute
  ResearchRoute: typeof ResearchRoute
  ResponsibleRoute: typeof ResponsibleRoute
  WorkflowRoute: typeof WorkflowRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible': {
      id: '/responsible'
      path: '/responsible'
      fullPath: '/responsible'
      preLoaderRoute: typeof ResponsibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  EmailRoute: EmailRoute,
  MeetingsRoute: MeetingsRoute,
  PlannerRoute: PlannerRoute,
  PromptsRoute: PromptsRoute,
  ResearchRoute: ResearchRoute,
  ResponsibleRoute: ResponsibleRoute,
  WorkflowRoute: WorkflowRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
